name: Clear README Cache

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clear README Image Cache
        run: |
          curl -H 'Authorization: token '${TOKEN}' -H 'Accept: application/vnd.github.v3.html' -sL ${url} \
          | grep -oE '<img src="https?://camo.githubusercontent.com/[^"]+' \
          | sed -e 's/<img src="//' \
          | while read url; do
            echo "Purging: $url"
            curl -sX PURGE "$url" -o /dev/null
          done
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: 'https://api.github.com/repos/myty/promise-chain/readme'
