name: Lint

on:
  pull_request: # on a pull request to each of these branches
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x

      - name: check format
        run: deno fmt --check

      - name: check linting
        run: deno lint
