name: Lint

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x

      - name: Check format
        run: deno fmt --check

      - name: Run Linter
        run: deno lint
