name: NPM
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  publish:
    name: Publishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: v1.43.x # Run with latest stable Deno.

      - name: Build and Test NPM Package
        run: deno run -A scripts/build_npm.ts ${{ github.ref }}
