name: Publish
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x

      - name: Check format
        run: deno fmt --check

      - name: Run Linter
        run: deno lint

      - name: Run Tests
        run: deno test

      - name: Build NPM Package
        run: deno run -A _build_npm.ts ${{ github.ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Publish NPM Package
        run: |
          cd npm
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
