name: Publish
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publishing
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/test.yml

      - name: Build NPM Package
        run: deno run -A _build_npm.ts ${{ github.ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Publish NPM Package
        run: |
          cd npm
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
