name: Test

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x

      - name: Run Tests
        run: deno test
