name: Test

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/lint.yml

      - name: Run Tests
        run: deno test
